### ISSUE TITLE
Demo scenario for Quarkus f2f

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/backstage-playground#111]
## Demo scenario

Part I:

- Create a quarkus application using the quarkus-application template
- show cd, pipelines and topology
- Show the actual app via the route

Part II:

- Create the quakrus-chatbot (select the exposed api from the previous step and also the component from the previous step)
- Show cd pipelines and topology
- Show the actual app via the route
- Ask the chatbot questions about your todo items. 
- The response should be consistent with what the first app has in its database.

**Comment by cmoulliard** [comment]
Question: Should we have a warning message top of the chatbot template or a way to check if ApiEntities exist and if not block the user to move to the next step ?

**Forget this question as I fixed it** : What should we encode under the fields: `API`, `ApiProvider` when we select the template chatbot ? @iocanel 

![Screenshot 2024-05-29 at 11 39 26](https://github.com/q-shift/backstage-playground/assets/463790/239fd64f-26b4-4ec8-aedc-2e2ab47f0e44)
=>
![Screenshot 2024-05-29 at 11 49 11](https://github.com/q-shift/backstage-playground/assets/463790/f3bcc628-c9b3-4191-a20d-19750c6cbcf8)

**Comment by cmoulliard** [comment]
The Tekton task step where maven test the chatbot application fails as no `dataSource` is defined using this generated project - https://github.com/ch007m/my-quarkus-chatbot
```
[ERROR] Errors: 
[ERROR]   GreetingResourceTest.testHelloEndpoint » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#configurationDescriptorBuilding threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Unable to find datasource '<default>' for persistence unit '<default>': Datasource '<default>' is not configured. To solve this, configure datasource '<default>'. Refer to https://quarkus.io/guides/datasource for guidance.
	at io.quarkus.hibernate.orm.runtime.PersistenceUnitUtil.unableToFindDataSource(PersistenceUnitUtil.java:112)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.handleHibernateORMWithNoPersistenceXml(HibernateOrmProcessor.java:842)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.configurationDescriptorBuilding(HibernateOrmProcessor.java:329)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Datasource '<default>' is not configured. To solve this, configure datasource '<default>'. Refer to https://quarkus.io/guides/datasource for guidance.
	at io.quarkus.datasource.common.runtime.DataSourceUtil.dataSourceNotConfigured(DataSourceUtil.java:47)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.handleHibernateORMWithNoPersistenceXml(HibernateOrmProcessor.java:843)
	... 13 more
```

The template is requesting 2 changes:
- starter parameter should be defined to false when we ask to the `quarkus:app` action to create a Quarkus app
- hibernate-orm-panache should be removed from the list of the extensions within the template OR user should be aware to not select it !!!

Remark: The user should be informed that they must create a secret containing the OpenAPI token !
```
kubectl create secret generic my-quarkus-chatbot --from-literal=openai-api-key=<OPENAPI_KEY>
```
@aureamunoz
