### ISSUE TITLE
Plugin 'auth' startup failed; caused by Error: Failed to initialize guest auth provider, The guest provider cannot be used outside of a development environment

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/backstage-playground#118]
## Issue

When the image "quay.io/ch007m/backstage-qshift-ocp" build for openshift is deployed on the cluster, then backstage reports this error
```
ForwardedError: Plugin 'auth' startup failed; caused by Error: Failed to initialize guest auth provider, The guest provider cannot be used outside of a development environment
at /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1859:17
at async /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1858:9
... 3 lines matching cause stack trace ...
at async BackstageBackend.start (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1949:5) {
cause: Error: Failed to initialize guest auth provider, The guest provider cannot be used outside of a development environment
```

A hack has been implemented in this backstage PR: https://github.com/backstage/backstage/pull/24188

**Comment by cmoulliard** [comment]
Fixed with #119
