### ISSUE TITLE
github personal token used to read/write a repository fails for iocanel

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/backstage-playground#171]
## Issue

The e2e process during the step to scaffold a quarkus app [fails](https://github.com/q-shift/backstage-playground/actions/runs/9677538448/job/26699394599) to create a github repository as `Permission to q-shift/my-quarkus-app-job.git denied to iocanel.`
```
  {
    "id": 109,
    "taskId": "43c7a09f-3e3a-4d70-ab69-084b87b8eb77",
    "body": {
      "message": "Error: HTTP Error: 403 Forbidden {data={\"statusCode\":403,\"statusMessage\":\"Forbidden\",\"response\":\"Permission to q-shift/my-quarkus-app-job.git denied to iocanel.\"}}\n    at _Git.push (/home/runner/work/backstage-playground/backstage-playground/node_modules/@backstage/plugin-scaffolder-backend-module-github/node_modules/@backstage/plugin-scaffolder-node/src/scm/git.ts:288:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Object.initRepoAndPush (/home/runner/work/backstage-playground/backstage-playground/node_modules/@backstage/plugin-scaffolder-backend-module-github/node_modules/@backstage/plugin-scaffolder-node/src/actions/gitHelpers.ts:74:3)\n    at initRepoPushAndProtect (/home/runner/work/backstage-playground/backstage-playground/node_modules/@backstage/plugin-scaffolder-backend-module-github/src/actions/helpers.ts:383:24)\n    at Object.handler (/home/runner/work/backstage-playground/backstage-playground/node_modules/@backstage/plugin-scaffolder-backend-module-github/src/actions/github.ts:259:28)\n    at NunjucksWorkflowRunner.executeStep (/home/runner/work/backstage-playground/backstage-playground/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:380:9)\n    at NunjucksWorkflowRunner.execute (/home/runner/work/backstage-playground/backstage-playground/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:513:9)\n    at TaskWorker.runOneTask (/home/runner/work/backstage-playground/backstage-playground/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:176:26)\n    at async run (/home/runner/work/backstage-playground/backstage-playground/node_modules/p-queue/dist/index.js:163:29)",
      "stepId": "publish-github",
      "status": "failed"
    },
  {
    "id": 104,
    "taskId": "92d87f17-61dd-4964-89d0-aa25901cf1fd",
    "body": {
      "message": "Run completed with status: failed",
      "error": {
        "name": "InputError",
        "message": "No token available for host: github.com, with owner q-shift, and repo my-quarkus-app-job"
      }
    },
    "type": "completion",
    "createdAt": "2024-06-26T15:24:10.000Z"
```
![Screenshot 2024-06-27 at 10 33 01](https://github.com/q-shift/backstage-playground/assets/463790/6ab11965-6fd7-47c5-85ff-d8935ef1b97e)

Here is the documentation page explaining how to manage the permissions of the tokens for an org: https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/setting-a-personal-access-token-policy-for-your-organization

Can you have a look please ? @iocanel

**Comment by iocanel** [comment]
It's not clear to me what settings I need to set to get this working.
Currently everything is enabled, with the only exception being the part where an admin needs to grant access per token. Still, no pending requests there. :confounded: 

In any case, I'll enable everything and please let me know if it makes any difference.

**Comment by cmoulliard** [comment]
Can we close this issue ? @iocanel
