### ISSUE TITLE
Switch to the new backend

### ISSUE THREAD

**Issue by cmoulliard** [q-shift/backstage-playground#88]
## TODO 

Switch to the new backend to be aligned with recent versions of backstage and to be also aligned with janus-idp which is using it too

**Comment by cmoulliard** [comment]
There is a module not_found error when we launch `yarn dev` which is coming from argocd backendmodule. To be investigated

```
[1] node:internal/modules/cjs/loader:1144
[1]   const err = new Error(message);
[1]               ^
[1] 
[1] Error: Cannot find module 'ent'
[1] Require stack:
[1] - /Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/node_modules/@google-cloud/storage/build/cjs/src/nodejs-common/util.js
[1] - /Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/node_modules/@google-cloud/storage/build/cjs/src/nodejs-common/service.js
[1] - /Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/node_modules/@google-cloud/storage/build/cjs/src/nodejs-common/index.js
[1] - /Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/node_modules/@google-cloud/storage/build/cjs/src/index.js
[1] - /Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/node_modules/@backstage/backend-app-api/node_modules/@backstage/backend-common/dist/index.cjs.js
[1] - /Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/node_modules/@backstage/backend-app-api/dist/index.cjs.js
[1] - /Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/node_modules/@backstage/backend-common/dist/index.cjs.js
[1] - /Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/dist/index.cjs.js
[1] - /Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-common/dist/index.cjs.js
[1] - /Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/dist/index.cjs.js
[1] - /Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/scaffolder-backend-argocd/dist/index.cjs.js
[1] - /Users/cmoullia/code/openshift/fork-backstage-playground/packages/backend/src/plugins/argocd-actions/plugin.ts
[1] - /Users/cmoullia/code/openshift/fork-backstage-playground/packages/backend/src/plugins/argocd-actions/index.ts
[1] - /Users/cmoullia/code/openshift/fork-backstage-playground/packages/backend/src/index.ts
[1]     at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
[1]     at Module._load (node:internal/modules/cjs/loader:985:27)
[1]     at Module.require (node:internal/modules/cjs/loader:1235:19)
[1]     at require (node:internal/modules/helpers:176:18)
[1]     at Object.<anonymous> (/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/node_modules/@google-cloud/storage/build/cjs/src/nodejs-common/util.js:49:26)
[1]     at Module._compile (node:internal/modules/cjs/loader:1376:14)
[1]     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
[1]     at Object.newLoader [as .js] (/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/pirates/lib/index.js:121:7)
[1]     at Module.load (node:internal/modules/cjs/loader:1207:32)
[1]     at Module._load (node:internal/modules/cjs/loader:1023:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1235:19)
[1]     at require (node:internal/modules/helpers:176:18)
[1]     at Object.<anonymous> (/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/node_modules/@google-cloud/storage/build/cjs/src/nodejs-common/service.js:28:19)
[1]     at Module._compile (node:internal/modules/cjs/loader:1376:14)
[1]     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
[1]     at Object.newLoader [as .js] (/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/pirates/lib/index.js:121:7) {
[1]   code: 'MODULE_NOT_FOUND',
[1]   requireStack: [
[1]     '/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/node_modules/@google-cloud/storage/build/cjs/src/nodejs-common/util.js',
[1]     '/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/node_modules/@google-cloud/storage/build/cjs/src/nodejs-common/service.js',
[1]     '/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/node_modules/@google-cloud/storage/build/cjs/src/nodejs-common/index.js',
[1]     '/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/node_modules/@google-cloud/storage/build/cjs/src/index.js',
[1]     '/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/node_modules/@backstage/backend-app-api/node_modules/@backstage/backend-common/dist/index.cjs.js',
[1]     '/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/node_modules/@backstage/backend-app-api/dist/index.cjs.js',
[1]     '/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/node_modules/@backstage/backend-common/dist/index.cjs.js',
[1]     '/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-app-api/dist/index.cjs.js',
[1]     '/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/node_modules/@backstage/backend-common/dist/index.cjs.js',
[1]     '/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/backstage-plugin-argo-cd-backend/dist/index.cjs.js',
[1]     '/Users/cmoullia/code/openshift/fork-backstage-playground/node_modules/@roadiehq/scaffolder-backend-argocd/dist/index.cjs.js',
[1]     '/Users/cmoullia/code/openshift/fork-backstage-playground/packages/backend/src/plugins/argocd-actions/plugin.ts',
[1]     '/Users/cmoullia/code/openshift/fork-backstage-playground/packages/backend/src/plugins/argocd-actions/index.ts',
[1]     '/Users/cmoullia/code/openshift/fork-backstage-playground/packages/backend/src/index.ts'
[1]   ]
[1] }
[1] 
[1] Node.js v20.11.0
[0] webpack compiled successfully
```

**Comment by cmoulliard** [comment]
When the following module is added, yarn reports a violation error fixed using more recent versions
```
yarn add @backstage/plugin-permission-backend-module-allow-all-policy
error Invariant Violation: expected workspace package to exist for "make-fetch-happen"
    at invariant (/Users/cmoullia/.cache/node/corepack/yarn/1.22.21/lib/cli.js:2318:15)
    at _loop2 (/Users/cmoullia/.cache/node/corepack/yarn/1.22.21/lib/cli.js:91024:9)
    at PackageHoister.init (/Users/cmoullia/.cache/node/corepack/yarn/1.22.21/lib/cli.js:91083:19)
    at PackageLinker.getFlatHoistedTree (/Users/cmoullia/.cache/node/corepack/yarn/1.22.21/lib/cli.js:48552:20)
    at PackageLinker.<anonymous> (/Users/cmoullia/.cache/node/corepack/yarn/1.22.21/lib/cli.js:48563:27)
    at Generator.next (<anonymous>)
    at step (/Users/cmoullia/.cache/node/corepack/yarn/1.22.21/lib/cli.js:310:30)
    at /Users/cmoullia/.cache/node/corepack/yarn/1.22.21/lib/cli.js:328:14
    at new Promise (<anonymous>)
    at new F (/Users/cmoullia/.cache/node/corepack/yarn/1.22.21/lib/cli.js:5540:28)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by cmoulliard** [comment]
Done with PR #94
